### ISSUE TITLE
error when running...  no idea

### ISSUE THREAD

**Issue by warriorsoul15** [shibdib/Dramiel#18]
Dramiel$ php Dramiel.php
PHP Fatal error:  Uncaught Error: Call to a member function sendMessage() on null in /home/menfi/Dramiel/src/plugins/onTick/getKillmails.php:168
Stack trace:
#0 /home/menfi/Dramiel/src/plugins/onTick/getKillmails.php(119): getKillmails->getKM()
#1 /home/menfi/Dramiel/Dramiel.php(145): getKillmails->tick()
#2 [internal function]: {closure}(Object(React\EventLoop\Timer\Timer))
#3 /home/menfi/Dramiel/vendor/react/event-loop/src/Timer/Timers.php(90): call_user_func(Object(Closure), Object(React\EventLoop\Timer\Timer))
#4 /home/menfi/Dramiel/vendor/react/event-loop/src/StreamSelectLoop.php(177): React\EventLoop\Timer\Timers->tick()
#5 /home/menfi/Dramiel/vendor/team-reflex/discord-php/src/Discord/WebSockets/WebSocket.php(927): React\EventLoop\StreamSelectLoop->run()
#6 /home/menfi/Dramiel/Dramiel.php(214): Discord\WebSockets\WebSocket->run()
#7 {main}

  thrown in /home/menfi/Dramiel/src/plugins/onTick/getKillmails.php on line 168

**Comment by warriorsoul15** [comment]
bad token, fixed.
